name: Verification

on:
  pull_request:
  workflow_dispatch:

jobs:
  style_check:
    name: "Check Code Styles"
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: "Setup Python"
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'pip'

      - name: "Check Python Code Format"
        run: |
          pip install -r <(cat requirements.txt | grep yapf)
          bash scripts/yapf.sh
  

  unit_test:
    name: "Test Code and Coverage"
    needs:
      - license_check
      - style_check
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: "Setup Python"
        id: python_cache
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'pip'

      - name: "Install Dependencies and Setup models"
        run: |
          pip install --upgrade pip
          pip install pipenv
          pip install -r requirements.txt

      - name: "Run Unit Tests"
        run: bash scripts/test.sh

      - name: "Run Pylint Code Analyzer"
        run: bash scripts/lint.sh